name: ht_sources_client
description: A Dart client interface for managing news sources.
repository: https://github.com/headlines-toolkit/ht-sources-client
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  equatable: ^2.0.7
  ht_countries_client:
    git:
      url: https://github.com/headlines-toolkit/ht-countries-client.git
  meta: ^1.16.0
  uuid: ^4.5.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
